### ISSUE TITLE
Error message when adding large files are not readable

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#895]
Originally from https://github.com/silverstripe/silverstripe-elemental-fileblock/issues/9

### Reproduce

1. Install `silverstripe/elemental-fileblock` on `2.x-dev` and  `dnadesign/silverstripe-elemental` on        `4.x-dev`
2. Create a page that has the ElementalPageExtension enabled
3. Add a FileBlock via the Add Block button
4. Click on the newly created File Block to expand it
5. Use the `Browse` link to add a file that is 2MB+
6. Observe an truncated error message as shown below

![image](https://user-images.githubusercontent.com/14869519/47880099-340cb780-de87-11e8-9669-5add90850b0e.png)

7. Hover over the error message and see that the tooltip does not show the entire message either

**Comment by clarkepaul** [comment]
I'm getting the same issue but also the error message isn't readable either. SS4.3 using large image.
![image](https://user-images.githubusercontent.com/555033/53048520-cfd73780-34f9-11e9-86e5-e4d9e057b9ee.png)

**Comment by ScopeyNZ** [comment]
Yeah it seems to just dump the response of the validation request verbatim. In your case it's obviously receiving some HTML page that it's dumping the source of 😞 .

**Comment by kinglozzer** [comment]
I suspect that https://github.com/silverstripe/silverstripe-asset-admin/issues/925 is the reason that @clarkepaul is seeing HTML instead of a friendly error message

**Comment by robbieaverill** [comment]
Note that the escaped HTML part of this is tracked here: https://github.com/silverstripe/silverstripe-asset-admin/issues/915

This issue should just address the fact that a message like "Filesize is too large" isn't able to be rendered. I believe someone made a PR that would show the full message as a title/hover tooltip, which is an improvement and might be enough to close this issue.

**Comment by brynwhyman** [comment]
Noting that this issue has been updated to include some new ACs. @silverstripeux noted that they want to have another look at the designs to check everything is in order

**Comment by sachajudd** [comment]
Updated designs can be found here: [Silverstripe CMS Design System](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/asset/componentContainers/5f5fffe36493f7b97c262d08/tab/design?mode=preview)

Few notes:
* Updated the padding on the basics component which should apply to all uploadfields
* Added an additional extended error uploadfield that grows in width depending on how long the error message is. This is to cater for longer messages or possible translations.
* 4 examples of error messaging.
* Added a mobile error uploadfield example.

Let me know if you have any thoughts or feedback 🙂

**Comment by emteknetnz** [comment]
@sachajudd DSM link isn't working for me, I've tried logging in an out.  Not sure what's going on

Could you take a screenshot of the design and post it here as a comment?

**Comment by sachajudd** [comment]
Sorted with @emteknetnz offline. Link is working correctly.

**Comment by emteknetnz** [comment]
Looks like this was indirectly fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/1138

This is how it now renders:

![image](https://user-images.githubusercontent.com/4809037/99928659-f1d8aa80-2dae-11eb-8b03-a6b89842bee7.png)

@brynwhyman you happy to close this?

**Comment by brynwhyman** [comment]
@emteknetnz the screenshot in the description looks to have a reduced-width. Have you tested that also?

I'm guessing that the messaging still won't be as responsive as we want it to be. When we looked at this issue, we felt that new designs would be the best way to solve the high-level bug that is: 'the error message is not readable'.

I wouldn't expect to close this issue until the following AC is met:
> New [design direction](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b5e6e3984472000117f3ee4) is followed

**Comment by emteknetnz** [comment]
![image](https://user-images.githubusercontent.com/4809037/100017945-863f1d80-2e40-11eb-8442-a08eb98be315.png)

Same width as original screenshot, still does not look particularly good

**Comment by sachajudd** [comment]
Agree with @brynwhyman to leave open until the new design direction has been followed.
